"""
AutoPR Agent — NotifierAgent

Creates GitHub Pull Request with rich natural language descriptions,
updates Work Item status in Linear/tracker, and dispatches team alerts to Discord.
"""

from __future__ import annotations

import logging
from typing import Any

from pydantic import BaseModel, Field

from autopr.agents.coder import CodeChanges
from autopr.agents.planner import ImplementationPlan
from autopr.config.models import get_model_client
from autopr.config.settings import get_settings
from autopr.mcp_servers import discord_server, github_server, linear_server

logger = logging.getLogger("autopr.agents.notifier")


class PRDescription(BaseModel):
    """Structured human-quality PR description generated by NotifierAgent."""

    title: str = Field(description="Conventional commit style PR title (e.g. 'feat(api): add request validation')")
    executive_summary: str = Field(description="High-level 2-3 sentence summary of changes")
    requirements_addressed: list[str] = Field(description="Bullet points of ticket requirements satisfied")
    architectural_notes: str = Field(description="Key design decisions or pattern adherence")
    test_evidence: str = Field(description="Summary of tests executed and validation results")


class NotificationResult(BaseModel):
    """Outcome of PR creation and team notifications."""

    pr_number: int
    pr_url: str
    pr_title: str
    pr_summary: str
    linear_updated: bool = False
    discord_notified: bool = False


class NotifierAgent:
    """Agent responsible for PR creation, description generation, and team notifications."""

    def __init__(self) -> None:
        self.settings = get_settings()
        self.model_client = get_model_client()

    async def notify_and_create_pr(
        self,
        work_item: dict[str, Any],
        plan: ImplementationPlan,
        changes: CodeChanges,
        branch_name: str,
    ) -> NotificationResult:
        """Generate PR, update ticket, and dispatch notifications.

        Args:
            work_item: Work item metadata.
            plan: The completed ImplementationPlan.
            changes: The CodeChanges summary and diff.
            branch_name: The feature branch name.

        Returns:
            NotificationResult instance.
        """
        item_id = str(work_item.get("identifier") or work_item.get("id") or plan.work_item_id)
        logger.info("NotifierAgent creating PR and notifications for %s on branch %s", item_id, branch_name)

        # 1. Generate Natural Language PR Description
        prompt = f"""
Generate an exceptional, human-quality Pull Request description for:
- **Work Item**: {item_id} — {plan.title}
- **Requirements**: {work_item.get('description', '')}
- **Target Files**: {changes.files_modified + changes.files_created}
- **Git Diff Preview**:
```
{changes.diff[:2500]}
```

Ensure the tone is professional, informative, and highlights test evidence.
"""

        pr_meta = self.model_client.generate(
            prompt=prompt,
            model=self.settings.default_model,
            response_schema=PRDescription,
        )

        if isinstance(pr_meta, PRDescription):
            pr_title = pr_meta.title or f"feat({item_id.lower()}): {plan.title}"
            reqs_markdown = "\n".join(f"- [x] {r}" for r in pr_meta.requirements_addressed)
            pr_body = f"""## 🚀 Summary
{pr_meta.executive_summary}

## 🎯 Work Item Traceability
Resolves **[{item_id}]**: {plan.title}

## ✅ Requirements Satisfied
{reqs_markdown}

## 🏗️ Architectural Notes
{pr_meta.architectural_notes}

## 🧪 Validation & Test Evidence
{pr_meta.test_evidence}
- **Files Modified**: `{', '.join(changes.files_modified) or 'None'}`
- **Files Created**: `{', '.join(changes.files_created) or 'None'}`

---
*Autonomous Pull Request created by [AutoPR](https://github.com/Sparrow375/AutoPR) • Google ADK 2.0*
"""
        else:
            pr_title = f"feat({item_id.lower()}): {plan.title}"
            pr_body = f"""## 🚀 Summary
Autonomously implemented changes for work item **{item_id}**: {plan.title}.

## 🎯 Work Item Traceability
Resolves **{item_id}**

## 🧪 Validation Evidence
- Automated test suite passed
- Ruff lint checks passed
- AST syntax audit verified

---
*Autonomous Pull Request created by [AutoPR](https://github.com/Sparrow375/AutoPR) • Google ADK 2.0*
"""

        # 2. Create Pull Request via GitHub MCP Server
        pr_record = github_server.create_pull_request(
            title=pr_title,
            body=pr_body,
            head_branch=branch_name,
            base_branch="main",
        )
        pr_url = pr_record.get("pr_url", f"https://github.com/Sparrow375/AutoPR/pull/{pr_record.get('pr_number', 1)}")
        pr_num = pr_record.get("pr_number", 1)

        # 3. Update Work Item in Linear / Tracker
        linear_updated = False
        try:
            await linear_server.update_issue_status(issue_id=item_id, status_name="Submitted for Review")
            await linear_server.add_comment(
                issue_id=item_id,
                comment=f"🎉 **AutoPR Completed**: Autonomous Pull Request created at {pr_url}\n\n{pr_title}",
            )
            linear_updated = True
        except Exception as e:
            logger.warning("Failed to update Linear ticket (%s)", e)

        # 4. Dispatch Discord Webhook Notification
        discord_notified = False
        try:
            discord_res = await discord_server.send_pipeline_update(
                event_type="PR_CREATED",
                status="success",
                details=f"Pull Request #{pr_num} autonomously created for {item_id}: **{pr_title}**",
                pr_url=pr_url,
                work_item_id=item_id,
            )
            discord_notified = discord_res.get("delivered", False)
        except Exception as e:
            logger.warning("Failed to dispatch Discord webhook (%s)", e)

        return NotificationResult(
            pr_number=pr_num,
            pr_url=pr_url,
            pr_title=pr_title,
            pr_summary=pr_body,
            linear_updated=linear_updated,
            discord_notified=discord_notified,
        )
